pre-release-commit-message = "{{crate_name}}: release version {{version}}"
post-release-commit-message = "{{crate_name}}: start next development iteration {{next_version}}"
consolidate-commits = true
